parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Drinks\Storefront\:
        resource: '../src/*'
        exclude: '../src/{App.php}'

    Drinks\Storefront\RequestHandler\RequestHandlersPool:
        arguments:
            - '@Drinks\Storefront\RequestHandler\Category'
            - '@Drinks\Storefront\RequestHandler\Cms'
            - '@Drinks\Storefront\RequestHandler\Product'

    Drinks\Storefront\Factory\ElasticsearchFactory:
        arguments:
            $url: '%env(string:ELASTIC_URL)%'

    Drinks\Storefront\Factory\RedisFactory:
        arguments:
            $uri: '%env(string:REDIS_URI)%'

    Drinks\Storefront\Factory\TwigFactory:
        arguments:
            $compileCachePath: '%env(string:TWIG_COMPILE_CACHE_PATH)%'
